### ISSUE TITLE
GetAsync vs GetStringAsync

### ISSUE THREAD

**Issue by mrappweareratio** [richardszalay/mockhttp#9] opened 2015-12-17 16:41 UTC
@richardszalay, could you provide insight as to why this test does not pass?

```
        [TestMethod]
        public async Task Test_MockHttp()
        {
            var mock = new MockHttpMessageHandler();
            var httpClient = new HttpClient(mock);
            mock.Expect("http://localhost.com")
                .Respond(HttpStatusCode.OK);
            await httpClient.GetAsync("http://localhost.com");

            _mockHttp.VerifyNoOutstandingExpectation();
            _mockHttp.Flush();

            mock.Expect("http://localhost.com")
                .Respond(HttpStatusCode.OK, new StringContent("test"));
            var s = await httpClient.GetStringAsync("http://localhost.com");
            Assert.AreEqual("test", s);
            _mockHttp.VerifyNoOutstandingExpectation();
        }
```

Test Name:	Test_MockHttp
Test Outcome:	Failed
Test Duration:	0:00:00.0167335

Result StackTrace:	
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at <Test_MockHttp>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	Test method Test_MockHttp threw exception: 
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (No matching mock handler).

Effectively, the expectations work with GetAsync but not with GetStringAsync.

**Comment by richardszalay** [comment] 2015-12-18 00:51
Looks like you've spotted a bug. I've committed a change and will try to do a new release as soon as I can.

In the meantime, if you add a trailing slash to your .When() it will work.

(The root cause is that SendAsync("http://localhost") passes through the Uri class, which serialises it to "http://localhost/", whereas .Expect("http://localhost") compares the strings, and so doesn't match)

**Comment by philipbjorge** [comment] 2016-03-01 19:59
@richardszalay -- Any ETA on a release? I just hit this...

**Comment by richardszalay** [comment] 2016-03-01 22:27
Just now!

https://www.nuget.org/packages/RichardSzalay.MockHttp/1.2.2

**Closed by richardszalay** 2016-03-01 22:27 UTC
